### ISSUE TITLE
Support target specific dependencies

### ISSUE THREAD

**Issue by svenfoo** [gdesmott/system-deps#33]
At `librsvg` we have a dependency on `pangoft2` and `fontconfig`, but not if you are building for Windows. I'd like to be able to express such a target-specific dependency using `system_deps`. Is that already possible, is such a feature planned?

**Comment by gdesmott** [comment]
This is currently not supported, no.

I'm open to adding specific API for this but I don't have any experience on any other platform than Linux so may need some help to design it.
I know about `#[cfg(target_os = "linux")]` for conditionally build blocks but I don't think that would do here. Is there any API we could use to fetch the platform info at runtime?

**Comment by gdesmott** [comment]
We could use [std::env::consts::OS](https://doc.rust-lang.org/std/env/consts/constant.OS.html).

@svenfoo  would something like this fit your use case?

```toml
[package.metadata.system-deps]
testdata = { version = "1", os = "linux" }
testlib = { version = "1", os = "macos" }
testmore = { version = "1", os = ["linux", "macos"] }
```

Or do you also need a way to enable a dep if the OS is **not** a specific one?
